options:
  formatter: stylish
  merge-default-rules: true
files:
  include: "**/*.s+(a|c)ss"
rules:
  class-name-format:
    - 0
  force-element-nesting:
    - 0
  force-pseudo-nesting:
    - 0
  nesting-depth:
    - 0
  no-color-literals:
    - 0
  no-ids:
    - 0
  no-important:
    - 0
