options:
  formatter: stylish
files:
  include: "**/*.s+(a|c)ss"
rules:
  empty-line-between-blocks:
    - 0
  hex-notation:
    - 1
    - style: uppercase
  indentation:
    - 1
    - size: 4
  nesting-depth:
    - 0
  no-css-comments:
    - 0
  no-ids:
    - 0
  no-important:
    - 0
  no-vendor-prefixes:
    - 0
  property-sort-order:
    - 1
    - order: alphabetical
      ignore-custom-properties: true
  pseudo-element:
    - 0
  quotes:
    - 1
    - style: double
  variable-name-format:
    - 1
    - allow-leading-underscore: false
      convention: pascalcase
